require 'rubygems' rescue nil
require 'net/http'
require 'lib/fogbugz_api'
require 'lib/fogbugz/query_builder'
require 'lib/fogbugz/xml_processor'
require 'lib/fogbugz/xml_response'
require 'lib/fogbugz/http_transport'
require 'lib/fogbugz/api'
require 'lib/fogbugz/api_helpers'
require 'lib/fogbugz/api_helpers_legacy'
require 'lib/fogbugz/fogbugz_http_api'
