require 'rubygems' rescue nil
require 'net/http'
require 'fogbugz/query_builder'
require 'fogbugz/xml'
require 'fogbugz/xml_processor'
require 'fogbugz/xml_response'
require 'fogbugz/http_transport'
require 'fogbugz/api'
require 'fogbugz/api_helpers'
require 'fogbugz/api_helpers_legacy'
require 'fogbugz/fogbugz'
require 'fogbugz/fogbugz_http_api'
